# Generated by Django 5.2.1 on 2025-10-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_alter_expense_options_expense_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
