# Generated by Django 5.2.1 on 2025-10-24 16:27

import django.core.validators
import gestor.models.expense
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=gestor.models.expense.today_date, verbose_name='Date'),
        ),
    ]
